### PR TITLE
Allow windows to find R in registry

### PR DESCRIPTION
**Pull request by jwtrubil**
A minor update to find R-base in windows registry.  This was causing errors when starting an r session.  It didn't seem to affect functionality though

### CODE REVIEW

**Comment by jalvesaq** [comment]
Thank you! However, please, see this: https://github.com/R-nvim/R.nvim/pull/223

I can't access any Windows machine to try your pull request, but it might be better to check both `HKCU` and `HKLM`.

**Comment by jwtrubil** [comment]
Thanks for that, I will look into what was done on R.nvim some more first.

**Comment by jalvesaq** [comment]
@jwtrubil could you try the branch "win_reg", please?

**Comment by jalvesaq** [comment]
I opened a pull request: https://github.com/jalvesaq/Nvim-R/pull/821

**Pull request closed without merging**
