### PR TITLE
WIP: Apple scripts to open/refresh HTML

### PR DESCRIPTION
**Pull request by itissid**
There is an issue with the safri script that I have not been able to diagnose, but chrome works just fine.

If you want I can remove the safari part and let the chrome part stay.

### CODE REVIEW

**Comment by jalvesaq** [comment]
We may let the Safari part too. Maybe someone else could fix it in the future.

**Comment by jalvesaq** [comment]
The browser is whathever is returned in R by `getOption("browser")`. That is, we don't need the `R_darwin_browser` option.

**Comment by jalvesaq** [comment]
I have just added the information about `getOption("browser")` to the documentation.

**Comment by jalvesaq** [comment]
You should replace
```
'osascript $HOME/.nvim/plugged/Nvim-R/R/tabrefresh_chrome.scpt '
```
with
```
'osascript ' . g:rplugin_home . ' /R/tabrefresh_chrome.scpt '
```

But I usually prefer to create a temporary file rather than having a permanent script in the Nvim-R directory. So, what are the contents of the scripts?

**Comment by itissid** [comment]
@jalvesaq Thanks for the comments. As you can see I haven't done much plugin programming. I was able to add 
```
'osascript ' . g:rplugin_home . ' /R/tabrefresh_chrome.scpt '
```
The safari browser works as well. The issue there was some double quotes in the `winname` argument that threw the command line off.

Chrome script:
https://gist.github.com/itissid/0725fc55ae837dcb0b40ce1b65511d50

Safari Script:
https://gist.github.com/itissid/e167e079fddc07a5b528b6bf8dbea784

There is some [history](https://apple.stackexchange.com/questions/163134/why-are-script-editor-scpt-files-not-saved-as-plain-text-files) about why these were saved as binary and not plain text. I think you already mentioned ^ that you were  planning to run `osacompile` and then put the binaries in Nvim-R at runtime(?).

Also am not sure how to call `getOption(browser)` were you thinking on the lines of adding an R function that did that?

**Comment by jalvesaq** [comment]
I'm sorry, but I don't want to put executable binaries in the source code.

nvimcom calls `getOption("browser")` on lines 250, 277 and 293 of R/nvimcom/R/nvim.interlace.R and pass the result to `ROpenDoc`.

**Comment by itissid** [comment]
that's fine. I am in the same page with you regarding the binaries. 

Could you tell me where I should place the compile statements for the scripts? I was thinking of doing so when the plugin installs. But being new to plugin programming I am not sure what might be the best place to do so.

Thanks

**Comment by jalvesaq** [comment]
I was expecting something simple, like this: https://github.com/jalvesaq/Nvim-R/blob/master/R/osx.vim#L50

**Comment by jalvesaq** [comment]
@itissid perhaps people could choose one of your two scripts, save it as `~/bin/tabrefresh.scpt`, make it executable and put in their `~/.Rprofile`:
```
options(browser = "/home/login/bin/tabfresh.scpt")
```

Then, I would avoid adding to the plugin a length (and binary) script that I cannot maintain.

**Comment by itissid** [comment]
@jalvesaq that sounds like an idea. Let me think about it for a bit. Thanks

**Comment by itissid** [comment]
I ll close this for now. It seems maintaining browser based scripts was too brittle. I have an idea to have a tiny electron app that might work in a more platform independent manner I ll code that up separately.

**Pull request closed without merging**
