### PR TITLE
 RCreateMaps: Create plug mappings unconditionally (fixes #470, fixes #494)

### LINKED ISSUE #470: <Plug> mappings don't work if made after vim loads (Esp RSendMotion)
I've reproduced minimally in terms of vimrc.

`:nmap q <Plug>RClearConsole`, then pressing `q` doesn't seem to do anything. No errors, either, so the plug mapping exists. This works in minimal repro.

`RSendMotion` doesn't work, even in minimal repro. `\m` does.

`nmap <LocalLeader>vd <Plug>RViewDF` is the same.

The mapping clearly exists:

`:map q`

> `n  q             <Plug>RSendMotion` 

When I set `verbose=99` and do `qw` on a letter, nothing is output.

Manually mapping it to what `\m` is set to works.

### LINKED ISSUE #494: <Plug> mappings cannot be defined as buffer-local (cannot use without overriding other mappings)
This is an issue to go with PR #472 and issue #470. It duplicates the information there.
It is a more precise version of #470, which was closed for a different bug.

Currently, `<plug>` mappings do not get defined unless the user has already mapped them in their `.vimrc`.
This means they cannot be set as buffer-local in a `autocmd filetype R`.

This means a user cannot map a key to the `<plug>` mappings that they use for a different shortcut in non-R buffers.
For example, if they use `<localleader>s` to send to their python REPL, they **cannot** override it and use `<localleader>s` in an R buffer for nvim-R send. If they do, and switch back to a python buffer, their `<localleader>s` is broken.
(But even if they don't use `<localleader>s` for python, but do want to use it for nvim-R, that means that all non-r buffers will also have their `<localleader>s` key trying to send to nvim-R.)

If you want a custom nvim-R mapping using `<Plug>`, you cannot re-use a mapping you use anywhere else.

### PR DESCRIPTION
**Pull request by BlueDrink9**
Previously, Plug mappings were only created if they were already in use - i.e., if someone had mapped them to something in their `.vimrc`. 

The problem with that is if someone wants to create buffer-local maps to an nvim-R <Plug> mapping, they cannot do so from .vimrc.
They must do so once the buffer is loaded - ie within vim, after loading .vimrc. This is usually done with an filetype autocmd.

This PR fixes that by making Nvim-R's `<Plug>R*` mappings always available, matching the behavior of most plugins that define <Plug> maps.

### CODE REVIEW

**Comment by jalvesaq** [comment]
The option `R_user_maps_only` was added on 2014 (https://github.com/jcfaria/Vim-R-plugin/commit/96fec1a033ca390610a6ca633d743159354f0e15).
We can either create a new option or add another possible value for `R_user_maps_only` (`2`, for example), but I don't want to change the default behavior of values `0` and `1`.

**Comment by BlueDrink9** [comment]
It doesn't change the behavior of that option, unless I'm forgetting something. As before, the creation of <Plug> mappings is independent of user_maps_only.

The only change that *might* affect users is that now, if a user has mapped to a <plug> mapping, the default mapping is still created. But that wasn't ever affected by user_maps_only anyway.

If you still think that change breaks compatibility, I think a new option would make more sense than re-using the other option. Something like `R_create_plug_maps_on_startup`?

**Comment by BlueDrink9** [comment]
@jalvesaq if you have time, could you please respond to the above and suggest how to move forward with this PR?

**Comment by jalvesaq** [comment]
This plugin is a file type plugin. Their maps must be available only for the file types that it supports. It doesn't make sense to have two maps for the same action.

**Comment by BlueDrink9** [comment]
<plug> maps don't really count as maps though. They are placeholders that don't interfere with the user experience until they decide to use them. Are you referring to <plug> maps?

Regarding your point about maps being only available for file types they support: That's what this PR allows. Under the current model, <plug> mappings *cannot* be filetype specific, because they cannot be set with a filetype autocommand. This PR fixes that. By your logic it should therefore be merged.

**Comment by BlueDrink9** [comment]
@jalvesaq are you able to respond to my previous comment, or would you like something else clarified or fixed?

**Comment by jalvesaq** [comment]
I don't remember who has proposed the use the `<Plug>` thing, but this happened many years ago and I would have to study again how file type plugins should create their maps, and I will not do this anytime soon. I'm much more busy in my job now than I was a few years ago. I believe that the current way of setting the key bindings is flexible enough. While you remain the only one complaining (in more than five years) I will keep assuming that Nvim-R does not have a bug on this issue.

**Comment by BlueDrink9** [comment]
Ok, I understand, thank you for the response. I will continue using my fork for now.

Would it help you (when you get time) for me to assemble examples of other plugins' use of `<plug>` mappings?

**Comment by jalvesaq** [comment]
> Would it help you (when you get time) for me to assemble examples of other plugins' use of `<plug>` mappings?

Yes, please.

**Comment by BlueDrink9** [comment]
Here is my list, I hope it helps convince you that the way nvim-R does it is non-standard, and that this pull request does not ask for abnormal behavior.

First up is vimtex, a popular (2.5k stars) latex plugin.

* [buffer-local `<plug>` imap defined without check for use](https://github.com/lervag/vimtex/blob/71370732506cf67f0526e0549316a4085e3d4ebf/autoload/vimtex/imaps.vim#L30)  
* [the majority of its buffer-local `<plug>` maps defined without check for use](https://github.com/lervag/vimtex/blob/001545e8a3ac81f4e6e3fb1302d409d8efb6361e/autoload/vimtex/motion.vim#L15)  
* [Same for motion mappings](https://github.com/lervag/vimtex/blob/878b8e860e0ef5ef52082579db4b6cf131689709/autoload/vimtex/text_obj/targets.vim#L20)  
* [They are only *used* if the user doesn't disable default mappings, but are declared regardless](https://github.com/lervag/vimtex/blob/5ce06b98333aa7f21a8332a90ef436efcef5f115/autoload/vimtex.vim#L474)
* [Note that this is how they are used even when mapped to local leader](https://github.com/lervag/vimtex/blob/5ce06b98333aa7f21a8332a90ef436efcef5f115/autoload/vimtex.vim#L485)

Plugin author Luc Hermitte uses them here:

* [LH-brackets (admittedly not an ftplugin)](https://github.com/LucHermitte/lh-brackets/blob/dc91bb1e8ef45a0810d9c1ad412863977c8c4baf/plugin/common_brackets.vim#L189)
* [Here, Luc uses them in a similar way to Nvim-R, except the ***opposite*** way around. They *are* *always* produced, but there is only a default map to them if they aren't otherwise used.](https://github.com/LucHermitte/lh-cpp/blob/0051ca77550e8a39fa1f609b3f24ccf5c7913260/ftplugin/c/c_navigate_functions.vim#L39)

And hopefully the nail in the coffin, the Vim sources themselves declare their `<plug>` mappings regardless of whether they are used.

* [The default plugin MatchIt.vim (responsible for `%`)](https://github.com/vim/vim/blob/eab6dff19f387469a200011bc6cf3508f5e43a4a/runtime/pack/dist/opt/matchit/plugin/matchit.vim#L49)
* [In fact, often the opposite behavior to Nvim-R](https://github.com/vim/vim/blob/a87b72cc316e065d66dcbcf7ec1cde330adef3a3/runtime/ftplugin/lprolog.vim#L23)

Also, adding `<Plug>` maps even if the user doesn't use them won't hurt anyone, because it doesn't pollute any namespaces or use up any key combinations. In conclusion, there should be nothing blocking this small PR that fixes inconsistent behaviour.

**Comment by jalvesaq** [comment]
I'm trying Nvim-R from your repository. Now, there a delay of about half a second to send lines to R. I have this in my init.vim:
```
nmap <Space> <Plug>RDSendLine
```

**Comment by BlueDrink9** [comment]
Can you also tell me the result of `:verbose nmap <space>`?

That sort of delay usually happens because you have something else mapped to `<space>[x]`, and vim waits `timeoutlen` milliseconds to see if you are going to push the next key in the sequence or leave it at just `<space>`

**Comment by jalvesaq** [comment]
The output is:
```
n  <Space>       <Plug>RDSendLine                                                                                                                                             
        Last set from ~/.config/nvim/init.vim line 405
```

**Comment by BlueDrink9** [comment]
Ok, I'll have a look when I have more time and see if I can reproduce it, or see what might be causing it.

It definitely doesn't appear if you keep the same init.vim but with your nvim-R instead of mine?

**Comment by BlueDrink9** [comment]
Oh, is your localleader also `<space>`? It could be because previous behaviour was not to define the default mapping _at all_ if a `<plug>` mapping is used. Currently, it will always define both unless `g:R_user_maps_only != 0`.

I can change that behaviour to still not define the default mapping if there is a `<plug>` mapping for that action, if you would prefer.

**Comment by jalvesaq** [comment]
My local leader is comma.

> It definitely doesn't appear if you keep the same init.vim but with your nvim-R instead of mine?

That was what I did. I renamed my Nvim-R directory and cloned yours.

> I can change that behaviour to still not define the default mapping if there is a <plug> mapping for that action, if you would prefer.

Yes.

**Comment by seb-mueller** [comment]
Just tried to understand this PR and it seems @BlueDrink9 has a point, according to `:h usr_41.txt`, `hasmapto` is exemplified with the reverse `!hasmapto`.

> But what if the user wants to define his own key sequence?  We can allow that
> with this mechanism: >
> 
>  21	if !hasmapto('<Plug>TypecorrAdd')
>  22	  map <unique> <Leader>a  <Plug>TypecorrAdd
>  23	endif
> 
> This checks if a mapping to "<Plug>TypecorrAdd" already exists, and only
> defines the mapping from "<Leader>a" if it doesn't.  The user then has a
> chance of putting this in his vimrc file: >
 
I'm gonna try out this PR to see if I can reproduce a delay.

**Comment by seb-mueller** [comment]
Giving the PR a go, everything seems to work fine, such as the default `<localleader>l` which is  mapped to `:call SendLineToR("stay")<CR>` instantaneous sends the line to R. 
However manually mapping `nmap <Space> <Plug>RDSendLine` does indeed result in a delay hitting space. Space is my leader which might wait for another input though, however mapping it to something else say `<F6>` instead of space still retains the delay. Changing back to before the PR, this delay seems indeed not to be there, so I'm a bit puzzled.

**Comment by BlueDrink9** [comment]
I can reproduce this using space with this minimal rc:

```sh
git clone https://github.com/BlueDrink9/Nvim-R.git /tmp/nvim-r
nvim -u NORC --cmd 'set rtp+=/tmp/nvim-r' -c 'nmap <space> <Plug>RDSendLine' -c 'call StartR("R")' test.r
```

**Comment by BlueDrink9** [comment]
> I can change that behaviour to still not define the default mapping if there is a mapping for that action, if you would prefer.

@jalvesaq this is now done.


Figured out what's causing it, although I'm not sure *why*, since it seems like bizarre vim behaviour.

Since this fork now defines all plug mappings even if not in use, there are 3 plug mappings that start with the same thing:

```vim
call RCreateMaps('ni0', 'RDSendLine', 'd', ':call SendLineToR("down")')
call RCreateMaps('ni0', 'RDSendLineAndInsertOutput', 'o', ':call SendLineToRAndInsertOutput()')
call RCreateMaps('v',   'RDSendLineAndInsertOutput', 'o', ':call RWarningMsg("This command does not work over a selection of lines.")')
```

Deleting the second two of these solves the problem.

[Lines are here](https://github.com/jalvesaq/Nvim-R/blob/db8dcff94c9f9d19a3971d6535b0cc727c2ebc72/R/common_global.vim#L2900)

Haven't got more time to look into it now.

**Comment by BlueDrink9** [comment]
maps to `<plug>RSendLine` don't have this issue either.

We need to check whether manually creating two `<plug>` maps with the same stem also cause this issue.

**Comment by BlueDrink9** [comment]
I have confirmed that it is in fact standard vim behavior.

The de-facto way to avoid this is to [surround the mapping name in brackets](https://stackoverflow.com/a/13698530/8170150). This seems to be convention in many plugins anyway.
In this case, the fix would look like a single change in mapping:
`call RCreateMaps('ni0', '(RDSendLine)', 'd', ':call SendLineToR("down")')`
(Or we could apply the change to the second two, since they are probably used less).

That brings us to a cross-roads, however. We have two people who really care about this (and given the non-standard behaviour of Nvim-R regarding declaration of `<plug>` mappings, I expect there are more that suffer silently).
However, to fix this and bring it up to convention, we need to make incompatible changes.
Given how stable this project has been, I can see how you might be reluctant to do that.

I don't think the impact would be too large, because if something breaks, a poweruser will come straight to the repo to look for the cause or complain. We could pin an issue highlighting the change, highlight it in the commit log, and/or the readme, so that they see the change.

**Comment by seb-mueller** [comment]
I'm much in favour of this PR since well justified by @BlueDrink9 . Also learned an awful lot along the way. I've just updated the this PR an haven't experienced any problems yet, but will keep testing.

**Comment by jalvesaq** [comment]
I've just tried Nvim-R from your repository again and still there is a delay when sending lines with my custom key binding (`<Space>`).

So, I'm thinking about doing the following:

1. Move the code that creates key bindings from `R/common_global.vim` to `R/kb_default.vim`.
2. Add a new option `R_key_bindings = "default"`.
3. In `R/common_global.vim` do:

```
exe "runtime R/kb_" . g:R_key_bindings . ".vim"
```

In this way, I can maintain more than one style of defining key bindings (currently, I don't want to do this) and the user could install other scripts maintained by other people which would define the key bindings in a different way.

What do you think about this proposal?

**Comment by BlueDrink9** [comment]
It doesn't seem like the ideal solution, and like you say it introduces a lot of extra code. The suggestions I made would fix it and bring it in line with vimscript standards.

I hadn't changed my repository version, because I was waiting on your response to my last comment. I have changed it now, so please try again. The delay should be gone.

**Comment by jalvesaq** [comment]
Thanks! I did only a very quick test and there was no delay anymore. So, I merged it.

**Pull request merged**
