### PR TITLE
Show name of R script in konsole window name

### PR DESCRIPTION
**Pull request by sjewo**
The term_cmd is adjusted to diplay "filename (full path to filename)" as window title in KDE konsole. This makes it easier to distinguish multiple terminal windows.

### CODE REVIEW

**Comment by jalvesaq** [comment]
I think the name of the script is not appropriate as Konsole window name because you will not be editing the script in this Konsole instance. The user can also switch to another R script in Vim and, then, the Konsole window title in addition to being inappropriate would be outdated.

**Comment by jalvesaq** [comment]
To be consistent with other terminal emulators supported by Nvim-R, the argument to pass to Konsole would be `-p tabtitle=R`.

**Comment by sjewo** [comment]
Your point is right - maybe my usecase isn't helpfull with different setups.

I use Nvim-R mostly with multiple gvim sessions, so the window title of the terminal window gives often no information about the gvim session it belongs to (especially if I open different files in the same directory).

**Comment by jalvesaq** [comment]
You could change the pull request to set the window title to "R" and put in your vimrc:
```
let R_term_cmd = "konsole -p tabtitle='". expand('%:t') ." (". expand('%:p') .")"."' --workdir '" . expand("%:p:h") . "'"
```

**Comment by sjewo** [comment]
Ok! Done. 

Thanks for the suggestion and your great plugin!

**Pull request merged**
