### PR TITLE
add elvish support

### PR DESCRIPTION
**Pull request by WERDXZ**
I'm using elvish as shell and trying to use tmux for split r cli, but its not working, so I made a little change( its not that elegant i think)

### CODE REVIEW

**Comment by jalvesaq** [comment]
I use `fish` shell, but this isn't relevant because I interact with R and not with the shell in the external terminal. Why can't you use `sh` as your shell in the external terminal?

**Comment by WERDXZ** [comment]
i think although /bin/sh interpret everything in bash but when you pass a command as a param to tmux it is interpreted as your default shell, in my case, the default shell is set as elvish in my environment variable, and it is giving the error:
```txt
Deprecation: the legacy temporary assignment syntax is deprecated; use "tmp" instead
  code from -c:1:1: TERM=screen-256color NVIMR_TMPDIR=/var/folders/qy/3l36x60n2zs1kw421gd3_2r00000gn/T/Nvim-R-werdxz NVIMR_COMPLDIR=/Users/werdxz/.cache/Nvim-R NVIMR_ID=3693838044 NVIMR_SECRET=2372643042 NVIMR_PORT=10101 R_DEFAULT_PACKAGES=datasets,utils,grDevices,graphics,stats,methods,nvimcom R
 ```
 :)
 thank you very much

**Comment by jalvesaq** [comment]
Could you try adding this to `R/external_term.sh`?

```vim
        if executable('/usr/bin/sh')
            let cnflines += ['set-option -g default-shell "/usr/bin/sh"']
        endif
```

**Comment by WERDXZ** [comment]
```vimscript
if executable('/bin/sh')
      let cnflines += ['set-option -g default-shell "/bin/sh"']
endif
```
I added this to the R/external_term.vim and it is working now. It is definitely a better to do the things above. thank you!

**Comment by jalvesaq** [comment]
Thank your for reporting the issue and for the feedback! The problem is fixed now.

**Comment by WERDXZ** [comment]
I did some more testing and find out that everywhere that need to interact with shell we might need to change it a bit like in file R/tmux_split.vim:102
could we split the command:
```
let scmd = "tmux set-buffer '" . str . "' && tmux paste-buffer -t " . g:rplugin.rconsole_pane
```
to like 
```
let scmd1 = "tmux set-buffer '" . str . "'"
let scmd2 = "tmux paste-buffer -t " . g:rplugin.rconsole_pane
```

in elvish we use `;` instead of `&&`

**Comment by jalvesaq** [comment]
Thanks! I made the changes since they work with `sh` too.

**Pull request closed without merging**
