### PR TITLE
Add Render function

### PR DESCRIPTION
**Pull request by ashiklom**
Similar functionality to Spin, except using the `rmarkdown` package function `render`. More on `rmarkdown` [here](http://rmarkdown.rstudio.com/authoring_quick_tour.html).

### CODE REVIEW

**Comment by mdlerch** [comment]
FYI, there's already `RMakeRmd` which I believe is already bound to `\kr` by default which calls `rmarkdown::render` through `nvimcom`.

**Comment by ashiklom** [comment]
@mdlerch That may be bound to `\kr` for `.Rmd` files, but, to my knowledge, not for `.R` scripts with markdown in the comments, following the general `spin` structure. But good to know -- if the scripts in `nvimcom` are the place to fix/include this then that's where they should be done. I just added this fix because it's one that I know works with my setup.

**Comment by mdlerch** [comment]
Interesting, I didn't realize that the same `render` function did "spin-ing" of  R-scripts.  I wonder if a better strategy, then, is to just move the corresponding lines in `ftplugin/rmd_nvimr.vim` to `ftplugin/r_nvimr.vim` so that they are available for `.R` as well as `.Rmd` rather than duplicating functionality.

I haven't investigated this myself yet, so maybe there is a reason this wouldn't work...

**Comment by ashiklom** [comment]
Yeah, in fact, I've never gotten `knitr::spin` to actually work with my `.R` scripts (error says that because it's formatted as `.Rmd`, I need to use `rmarkdown::render`), whereas `rmarkdown::render` works every time with the default arguments. Maybe I've been formatting my R scripts for spinning wrong, but either way, it's an easy feature to add.

**Comment by jalvesaq** [comment]
I don't use either spin or render, so I will merge whatever you two agree that is the best option. Any conclusion so far?

**Comment by mdlerch** [comment]
I sent @ashiklom a patch a little earlier that moves the `rmarkdown::render()` logic from `ftplugin/rmd_nvimr.vim` to `R/common_global.vim` since apparently it is viable for various R file types.  The benefit of using the existing code is that we can render to many different output types and also not replicate code.  Either way I think is reasonable though.  Whatever @ashiklom thinks looks good is fine with me!

**Comment by ashiklom** [comment]
The fix @mdlerch suggested works great! I agree that it's the better approach since it leverages existing code and is more flexible. I think this is ready to merge.

**Pull request merged**
